name: Label Triggered PR to Main

on:
  pull_request:
    types:
      - labeled

jobs:
  pr-to-main:
    if: github.event.pull_request.state == 'closed' && github.event.label.name == 'merge-to-main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Fetch all branches
        run: git fetch --all

      - name: Checkout main branch
        run: git checkout main

      - name: Cherry-pick the PR commit(s) into main
        run: |
          git cherry-pick -x ${{ github.event.pull_request.head.sha }}

      - name: Push changes to main branch
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_PAT }}
        run: |
          echo "Using GITHUB_TOKEN: ${{ secrets.ACTIONS_PAT }}"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
          git push origin main
