name: Label Triggered PR to Main

on:
  pull_request:
    types:
      - labeled

jobs:
  pr-to-main:
    if: github.event.pull_request.state == 'closed' && github.event.label.name == 'merge-to-main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Fetch all branches
        run: git fetch --all

      - name: Checkout main branch
        run: |
          git checkout main
          git checkout dev


      - name: Cherry-pick the entire range of PR commits into main
        run: |
          # Identify the base commit (before the PR) and the head commit (last commit in the PR)
          BASE_COMMIT=$(git merge-base origin/dev origin/${{ github.event.pull_request.head.ref }})
          echo $BASE_COMMIT
          HEAD_COMMIT=${{ github.event.pull_request.head.sha }}
          
          # Cherry-pick all commits from the PR range
          git cherry-pick ${BASE_COMMIT}..${HEAD_COMMIT}

      - name: Push changes to main branch
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_PAT }}
        run: |
          echo "Using GITHUB_TOKEN: ${{ secrets.ACTIONS_PAT }}"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
          git push origin main
