name: Handle PR Label

on:
  pull_request:
    types: [labeled]

jobs:
  get-commits:
    if: github.event.pull_request.state == 'closed' && contains(github.event.pull_request.labels.*.name, 'merge-to-main')
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get PR Commits
      run: |
        PR_NUMBER=${{ github.event.pull_request.number }}
        COMMITS=$(gh pr view $PR_NUMBER --json commits --jq '.commits[].commit.message')
        echo "Commits in PR #${PR_NUMBER}:"
        echo "$COMMITS"

    - name: List PR Commits
      run: |
        PR_NUMBER=${{ github.event.pull_request.number }}
        git fetch origin
        git log --pretty=format:"%H %s" $(git merge-base origin/main HEAD)..HEAD
